name: build and push

on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        pull: true
        push: true
        labels: org.opencontainers.image.version=${{ github.ref_name }}
        tags: ${{ secrets.DOCKERHUB_REPO }}/google_403_domains:latest,${{ secrets.DOCKERHUB_REPO }}/google_403_domains:${{ github.ref_name }}
